# Generated by Django 4.1.7 on 2023-03-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '前台'), (2, '档案室'), (3, '诊室'), (4, '免疫室'), (5, '化验室'), (6, '影像室'), (7, '专科检查室'), (8, '处置室'), (9, '药房'), (10, '注射室'), (11, '手术准备室'), (12, '手术室'), (13, '住院部'), (14, '病理剖检室')], default=0)),
                ('description', models.TextField(max_length=1000)),
                ('reserved1', models.TextField(max_length=1000)),
                ('reserved2', models.TextField(max_length=1000)),
                ('reserved3', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department_name', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '前台'), (2, '档案室'), (3, '诊室'), (4, '免疫室'), (5, '化验室'), (6, '影像室'), (7, '专科检查室'), (8, '处置室'), (9, '药房'), (10, '注射室'), (11, '手术准备室'), (12, '手术室'), (13, '住院部'), (14, '病理剖检室')], default=0)),
                ('description', models.TextField(max_length=1000)),
                ('reserved1', models.TextField(max_length=1000)),
                ('reserved2', models.TextField(max_length=1000)),
                ('reserved3', models.TextField(max_length=1000)),
            ],
        ),
    ]
