# Generated by Django 4.1.7 on 2023-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='reserved1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='reserved2',
        ),
        migrations.RemoveField(
            model_name='department',
            name='reserved3',
        ),
        migrations.RemoveField(
            model_name='role',
            name='reserved1',
        ),
        migrations.RemoveField(
            model_name='role',
            name='reserved2',
        ),
        migrations.RemoveField(
            model_name='role',
            name='reserved3',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[('', ''), ('前台', '前台'), ('档案室', '档案室'), ('诊室', '诊室'), ('免疫室', '免疫室'), ('化验室', '化验室'), ('影像室', '影像室'), ('7', '专科检查室'), ('8', '处置室'), ('9', '药房'), ('10', '注射室'), ('11', '手术准备室'), ('12', '手术室'), ('13', '住院部'), ('14', '病理剖检室')], default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='department_name',
            field=models.PositiveSmallIntegerField(choices=[('', ''), ('前台', '前台'), ('档案室', '档案室'), ('诊室', '诊室'), ('免疫室', '免疫室'), ('化验室', '化验室'), ('影像室', '影像室'), ('7', '专科检查室'), ('8', '处置室'), ('9', '药房'), ('10', '注射室'), ('11', '手术准备室'), ('12', '手术室'), ('13', '住院部'), ('14', '病理剖检室')], default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
