version: '3'

services:
  web:
    restart: always
    build: .
    command: /bin/bash -c "
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_PASSWORD: 123456
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: 123@123.com
    depends_on:
      - mariadb
    networks:
      - server
  mariadb:
    image: "mariadb:10.11"
    hostname: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - server
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clinic

volumes:
  db_data:

networks:
  server: