version: '3'
services:
  db:
    image: "mariadb:10.11"
    ports:
      - "3366:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: clinic
