# Generated by Django 4.1.7 on 2023-03-15 07:50

import django.core.validators
from django.db import migrations, models
import quiz.models
import quiz.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('answerA', models.BooleanField(default=False)),
                ('answerB', models.BooleanField(default=False)),
                ('answerC', models.BooleanField(default=False)),
                ('answerD', models.BooleanField(default=False)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('duration', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(10)])),
                ('students', models.JSONField(validators=[quiz.validators.JsonFieldValidator(['list'])])),
                ('questions', models.JSONField(validators=[quiz.validators.JsonFieldValidator([quiz.models.QuestionType['SINGLE'], quiz.models.QuestionType['MULTI'], quiz.models.QuestionType['TRUEORFALSE'], quiz.models.QuestionType['TEXT']])])),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('optionA', models.CharField(max_length=100, verbose_name='Option A')),
                ('optionB', models.CharField(max_length=100, verbose_name='Option B')),
                ('optionC', models.CharField(max_length=100, verbose_name='Option C')),
                ('optionD', models.CharField(max_length=100, verbose_name='Option D')),
                ('answer', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, max_length=10)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('answer', models.CharField(choices=[(1, '对'), (0, '错')], default=0, max_length=20)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
