# Generated by Django 4.1.7 on 2023-03-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleChoiceQuestion',
        ),
    ]
