# Generated by Django 4.1.7 on 2023-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_singlechoicequestion_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('answer', models.BooleanField(default=False)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5)),
            ],
        ),
    ]
