# Generated by Django 4.1.7 on 2023-03-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_tfquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TFQuestion',
            new_name='TrueOrFalseQuestion',
        ),
    ]
