# Generated by Django 4.1.7 on 2023-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_tfquestion_trueorfalsequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('answerA', models.BooleanField(default=False)),
                ('answerB', models.BooleanField(default=False)),
                ('answerC', models.BooleanField(default=False)),
                ('answerD', models.BooleanField(default=False)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('disease_type', models.CharField(choices=[('infectious', '传染病'), ('parasitic', '寄生虫病'), ('internal', '内科'), ('obstetric', '外产科疾病'), ('surgery', '常用手术'), ('immunology', '免疫')], default='internal', max_length=20)),
                ('score', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='answer',
            field=models.CharField(choices=[(1, '对'), (0, '错')], default=0, max_length=20),
        ),
    ]
