# Generated by Django 4.1.7 on 2023-03-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='', max_length=100, unique=True)),
                ('disease_type', models.CharField(default='', max_length=100)),
                ('disease_name', models.CharField(default='', max_length=100)),
                ('pet_name', models.CharField(default='', max_length=100)),
                ('pet_species', models.CharField(default='', max_length=100)),
                ('pet_age', models.IntegerField(default=-1)),
                ('owner_name', models.CharField(default='', max_length=100)),
                ('owner_phone', models.CharField(default='', max_length=100)),
                ('symptom', models.JSONField(default=dict)),
                ('diagnosis_result', models.JSONField(default=dict)),
                ('treatment', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('key', models.CharField(default='', max_length=1000)),
                ('children', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='', max_length=100)),
                ('checkup_item', models.CharField(default='', max_length=100)),
                ('checkup_result', models.JSONField(default=dict)),
                ('checkup_pic', models.ImageField(default='E:\\ALin\\test.jpg', upload_to='images/')),
            ],
        ),
    ]
