# Generated by Django 4.1.7 on 2023-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(default='', max_length=100)),
                ('disease_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
