# Generated by Django 4.1.7 on 2023-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='category',
            name='disease_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='disease_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.JSONField(default=dict),
        ),
    ]
