# Generated by Django 4.1.7 on 2023-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='case_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
