# Generated by Django 4.1.7 on 2023-03-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_checkup_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
